name: Ada (GNAT)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update &&
        sudo apt-get install gnat gprbuild
        
    - name: Install AUnit
      run: |
        git clone https://github.com/AdaCore/aunit.git
        cd aunit
        gprbuild -P aunit.gpr
        

    - name: Build
      run: > 
        /bin/bash bin/jenkins.sh
