name: Ada (GNAT)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v2
      with:
        path: ./cached_gnat
        key: ${{ runner.os }}-gnat-ce-2020
        
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install GNAT
      uses: ada-actions/toolchain@dev
      with:
        distrib: community
        target: arm-elf
        install_dir: ./cached_gnat


        
    - name: Build
      run: > 
        /bin/bash bin/jenkins.sh
